// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (job_id, status, notes)
VALUES($1, 'new', $2)
RETURNING id, job_id, status, applied_at, notes, next_action, next_action_date, created_at
`

type CreateApplicationParams struct {
	JobID int64
	Notes pgtype.Text
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication, arg.JobID, arg.Notes)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Status,
		&i.AppliedAt,
		&i.Notes,
		&i.NextAction,
		&i.NextActionDate,
		&i.CreatedAt,
	)
	return i, err
}

const getApplication = `-- name: GetApplication :one
SELECT id, job_id, status, applied_at, notes, next_action, next_action, next_action_date, created_at
FROM applications
WHERE id = $1
`

type GetApplicationRow struct {
	ID             int64
	JobID          int64
	Status         string
	AppliedAt      pgtype.Timestamptz
	Notes          pgtype.Text
	NextAction     pgtype.Text
	NextAction_2   pgtype.Text
	NextActionDate pgtype.Date
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) GetApplication(ctx context.Context, id int64) (GetApplicationRow, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i GetApplicationRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Status,
		&i.AppliedAt,
		&i.Notes,
		&i.NextAction,
		&i.NextAction_2,
		&i.NextActionDate,
		&i.CreatedAt,
	)
	return i, err
}

const listApplications = `-- name: ListApplications :many
SELECT a.id, a.job_id, a.status, a.applied_at, a.notes,
        a.next_action, a.next_action_date, a.created_at, 
        j.title, j.company, j.url
FROM applications a
JOIN jobs j ON j.id = a.job_id
ORDER BY a.created_at DESC
`

type ListApplicationsRow struct {
	ID             int64
	JobID          int64
	Status         string
	AppliedAt      pgtype.Timestamptz
	Notes          pgtype.Text
	NextAction     pgtype.Text
	NextActionDate pgtype.Date
	CreatedAt      pgtype.Timestamptz
	Title          string
	Company        string
	Url            string
}

func (q *Queries) ListApplications(ctx context.Context) ([]ListApplicationsRow, error) {
	rows, err := q.db.Query(ctx, listApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApplicationsRow
	for rows.Next() {
		var i ListApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Status,
			&i.AppliedAt,
			&i.Notes,
			&i.NextAction,
			&i.NextActionDate,
			&i.CreatedAt,
			&i.Title,
			&i.Company,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications
SET status = COALESCE($2, status),
        notes = COALESCE($3, notes),
        next_action = COALESCE($4, next_action),
        applied_at = CASE
                WHEN $2::text = 'applied' AND applied_at IS NULL THEN now()
                ELSE applied_at
        END
WHERE id = $1
RETURNING id, job_id, status, applied_at, notes, next_action, next_action_date, created_at
`

type UpdateApplicationParams struct {
	ID         int64
	Status     pgtype.Text
	Notes      pgtype.Text
	NextAction pgtype.Text
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication,
		arg.ID,
		arg.Status,
		arg.Notes,
		arg.NextAction,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Status,
		&i.AppliedAt,
		&i.Notes,
		&i.NextAction,
		&i.NextActionDate,
		&i.CreatedAt,
	)
	return i, err
}
