// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJobs = `-- name: CountJobs :one
SELECT count(*) FROM jobs
`

func (q *Queries) CountJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    title, company, source, url, description, description_hash, location, remote, posted_at, hash, raw_json
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11 
)
ON CONFLICT (hash) DO NOTHING
RETURNING id
`

type CreateJobParams struct {
	Title           string
	Company         string
	Source          string
	Url             string
	Description     string
	DescriptionHash string
	Location        string
	Remote          bool
	PostedAt        pgtype.Timestamptz
	Hash            string
	RawJson         []byte
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Title,
		arg.Company,
		arg.Source,
		arg.Url,
		arg.Description,
		arg.DescriptionHash,
		arg.Location,
		arg.Remote,
		arg.PostedAt,
		arg.Hash,
		arg.RawJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
