// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJobs = `-- name: CountJobs :one
SELECT count(*) FROM jobs
`

func (q *Queries) CountJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    title, company, source, url, description, description_hash, location, remote, posted_at, hash, raw_json
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11 
)
ON CONFLICT (hash) DO NOTHING
RETURNING id
`

type CreateJobParams struct {
	Title           string
	Company         string
	Source          string
	Url             string
	Description     string
	DescriptionHash string
	Location        string
	Remote          bool
	PostedAt        pgtype.Timestamptz
	Hash            string
	RawJson         []byte
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Title,
		arg.Company,
		arg.Source,
		arg.Url,
		arg.Description,
		arg.DescriptionHash,
		arg.Location,
		arg.Remote,
		arg.PostedAt,
		arg.Hash,
		arg.RawJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, title, company, source, url, location, remote, posted_at, link_status, created_at
FROM jobs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit  int32
	Offset int32
}

type ListJobsRow struct {
	ID         int64
	Title      string
	Company    string
	Source     string
	Url        string
	Location   string
	Remote     bool
	PostedAt   pgtype.Timestamptz
	LinkStatus string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]ListJobsRow, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsRow
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Source,
			&i.Url,
			&i.Location,
			&i.Remote,
			&i.PostedAt,
			&i.LinkStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
