// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countJobs = `-- name: CountJobs :one
SELECT count(*) FROM jobs
`

func (q *Queries) CountJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    title, company, source, url, description, description_hash, location, remote, posted_at, hash, raw_json
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11 
)
ON CONFLICT (hash) DO NOTHING
RETURNING id
`

type CreateJobParams struct {
	Title           string
	Company         string
	Source          string
	Url             string
	Description     string
	DescriptionHash string
	Location        string
	Remote          bool
	PostedAt        pgtype.Timestamptz
	Hash            string
	RawJson         []byte
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Title,
		arg.Company,
		arg.Source,
		arg.Url,
		arg.Description,
		arg.DescriptionHash,
		arg.Location,
		arg.Remote,
		arg.PostedAt,
		arg.Hash,
		arg.RawJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createJobScore = `-- name: CreateJobScore :one
INSERT INTO job_scores (
    job_id, fit_score, dimension_scores, matched_skills, missing_skills, rationale
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id
`

type CreateJobScoreParams struct {
	JobID           int64
	FitScore        int32
	DimensionScores []byte
	MatchedSkills   []string
	MissingSkills   []string
	Rationale       pgtype.Text
}

func (q *Queries) CreateJobScore(ctx context.Context, arg CreateJobScoreParams) (int64, error) {
	row := q.db.QueryRow(ctx, createJobScore,
		arg.JobID,
		arg.FitScore,
		arg.DimensionScores,
		arg.MatchedSkills,
		arg.MissingSkills,
		arg.Rationale,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listJobs = `-- name: ListJobs :many
SELECT j.id, j.title, j.company, j.source, j.url, j.location, j.remote,
       j.posted_at, j.link_status, j.created_at,
       s.fit_score, s.rationale
FROM jobs j
LEFT JOIN job_scores s ON s.job_id = j.id
ORDER BY 
    CASE WHEN $3::bool THEN s.fit_score END DESC NULLS LAST,
    j.created_at DESC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit       int32
	Offset      int32
	SortByScore bool
}

type ListJobsRow struct {
	ID         int64
	Title      string
	Company    string
	Source     string
	Url        string
	Location   string
	Remote     bool
	PostedAt   pgtype.Timestamptz
	LinkStatus string
	CreatedAt  pgtype.Timestamptz
	FitScore   pgtype.Int4
	Rationale  pgtype.Text
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]ListJobsRow, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.Offset, arg.SortByScore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsRow
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Source,
			&i.Url,
			&i.Location,
			&i.Remote,
			&i.PostedAt,
			&i.LinkStatus,
			&i.CreatedAt,
			&i.FitScore,
			&i.Rationale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnscoredJobs = `-- name: ListUnscoredJobs :many
SELECT j.id, j.title, j.company, j.source, j.url, j.description, j.description_hash, j.location, j.posted_at
FROM jobs j
LEFT JOIN job_scores s ON s.job_id = j.id
WHERE s.id IS NULL
ORDER BY j.created_at DESC
LIMIT $1
`

type ListUnscoredJobsRow struct {
	ID              int64
	Title           string
	Company         string
	Source          string
	Url             string
	Description     string
	DescriptionHash string
	Location        string
	PostedAt        pgtype.Timestamptz
}

func (q *Queries) ListUnscoredJobs(ctx context.Context, limit int32) ([]ListUnscoredJobsRow, error) {
	rows, err := q.db.Query(ctx, listUnscoredJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnscoredJobsRow
	for rows.Next() {
		var i ListUnscoredJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Company,
			&i.Source,
			&i.Url,
			&i.Description,
			&i.DescriptionHash,
			&i.Location,
			&i.PostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
