// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID             int64
	JobID          int64
	Status         string
	AppliedAt      pgtype.Timestamptz
	Notes          pgtype.Text
	NextAction     pgtype.Text
	NextActionDate pgtype.Date
	CreatedAt      pgtype.Timestamptz
}

type Blacklist struct {
	ID    int64
	Type  string
	Value string
}

type Draft struct {
	ID            int64
	ApplicationID int64
	CoverLetter   pgtype.Text
	CustomAnswers []byte
	Version       int32
	CreatedAt     pgtype.Timestamptz
}

type Job struct {
	ID              int64
	Title           string
	Company         string
	Source          string
	Url             string
	Description     string
	DescriptionHash string
	Location        string
	Remote          bool
	PostedAt        pgtype.Timestamptz
	Hash            string
	LinkStatus      string
	RawJson         []byte
	CreatedAt       pgtype.Timestamptz
}

type JobScore struct {
	ID              int64
	JobID           int64
	FitScore        int32
	DimensionScores []byte
	MatchedSkills   []string
	MissingSkills   []string
	Rationale       pgtype.Text
	ScoredAt        pgtype.Timestamptz
}

type SourceLog struct {
	ID         int64
	SourceName string
	FetchedAt  pgtype.Timestamptz
	JobsFound  int32
	JobsNew    int32
	Errors     pgtype.Text
	DurationMs int64
}

type UserProfile struct {
	ID               int64
	Name             string
	CurrentRoleTitle pgtype.Text
	Skills           []string
	ExperienceYears  pgtype.Int4
	TargetRoles      []string
	PreferredStack   []string
	SalaryMin        pgtype.Int4
	SalaryMax        pgtype.Int4
	LocationPref     pgtype.Text
	RemoteOnly       bool
	Timezone         string
	UpdatedAt        pgtype.Timestamptz
}
