// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProfile = `-- name: GetProfile :one
SELECT id, name, current_role_title, skills, experience_years, target_roles, preferred_stack, salary_min, salary_max, location_pref, remote_only, timezone, updated_at
FROM user_profile
WHERE id = 1
`

func (q *Queries) GetProfile(ctx context.Context) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getProfile)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrentRoleTitle,
		&i.Skills,
		&i.ExperienceYears,
		&i.TargetRoles,
		&i.PreferredStack,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.LocationPref,
		&i.RemoteOnly,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProfile = `-- name: UpsertProfile :one
INSERT INTO user_profile (
    id, name, current_role_title, skills, experience_years,
    target_roles, preferred_stack, salary_min, salary_max,
    location_pref, remote_only, timezone, updated_at
) VALUES (
    1, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now()
)
ON CONFLICT (id) DO UPDATE SET 
    name                 = EXCLUDED.name,
    current_role_title   = EXCLUDED.current_role_title,
    skills               = EXCLUDED.skills,
    experience_years     = EXCLUDED.experience_years,
    target_roles         = EXCLUDED.target_roles,
    preferred_stack      = EXCLUDED.preferred_stack,
    salary_min           = EXCLUDED.salary_min,
    salary_max           = EXCLUDED.salary_max,
    location_pref        = EXCLUDED.location_pref,
    remote_only          = EXCLUDED.remote_only,
    timezone             = EXCLUDED.timezone,
    updated_at           = now()
RETURNING id, name, current_role_title, skills, experience_years,
          target_roles, preferred_stack, salary_min, salary_max,
          location_pref, remote_only, timezone, updated_at
`

type UpsertProfileParams struct {
	Name             string
	CurrentRoleTitle pgtype.Text
	Skills           []string
	ExperienceYears  pgtype.Int4
	TargetRoles      []string
	PreferredStack   []string
	SalaryMin        pgtype.Int4
	SalaryMax        pgtype.Int4
	LocationPref     pgtype.Text
	RemoteOnly       bool
	Timezone         string
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, upsertProfile,
		arg.Name,
		arg.CurrentRoleTitle,
		arg.Skills,
		arg.ExperienceYears,
		arg.TargetRoles,
		arg.PreferredStack,
		arg.SalaryMin,
		arg.SalaryMax,
		arg.LocationPref,
		arg.RemoteOnly,
		arg.Timezone,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CurrentRoleTitle,
		&i.Skills,
		&i.ExperienceYears,
		&i.TargetRoles,
		&i.PreferredStack,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.LocationPref,
		&i.RemoteOnly,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}
